import Vue from 'vue'
import { Button, Form, FormItem, Input, Message, container, Header,Aside, Main, Menu, Submenu,
    MenuItemGroup,Popover, MenuItem, Breadcrumb, BreadcrumbItem, Card, select, Option, Col, Row, Table, TableColumn, Pagination, Dialog, DatePicker,Checkbox,CheckboxGroup,Tag,Collapse,CollapseItem} from 'element-ui'

Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(select)
Vue.use(Option)
Vue.use(Col)
Vue.use(Row)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Pagination)
Vue.use(Dialog)
Vue.use(DatePicker)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(Tag)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Popover)
Vue.prototype.$message = Message
